### ISSUE TITLE
Inflate Exception

### ISSUE THREAD

**Issue by ravibhan90** [ApmeM/android-flowlayout#49]
The app is crashing on some device and this is the stack trace .  I am using  flowlayout inside relative layout with basic configuration , the xml code is attached below. Any ideas how to fix this.

Android version - Android 4.0.3 - 4.0.4
Device - Xperia Miro (ST23i)

android.view.InflateException: Binary XML file line #230: Error inflating class o.mz
at android.view.LayoutInflater.createView(LayoutInflater.java:606)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at com.oodles.download.free.ebooks.reader.fragments.BookDetailsFragment.onCreateView$469ccb8a(BookDetailsFragment.java:132)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:953)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1136)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1499)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:456)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Constructor.java)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:586)
... 22 more
Caused by: java.lang.NullPointerException
at org.apmem.tools.layouts.LayoutConfiguration.getLayoutDirection(LayoutConfiguration.java:73)
at org.apmem.tools.layouts.FlowLayout.getLayoutDirection(FlowLayout.java:427)
at android.view.View.resolveLayoutDirectionIfNeeded(View.java:9633)
at android.view.View.getResolvedLayoutDirection(View.java:4826)
at android.view.View.setPaddingRelative(View.java:12034)
at android.view.View.setPadding(View.java:11945)
at android.view.ViewGroup.setPadding(ViewGroup.java:2378)
at android.view.View.(View.java:3108)
at android.view.View.(View.java:2735)
at android.view.ViewGroup.(ViewGroup.java:413)
at org.apmem.tools.layouts.FlowLayout.(FlowLayout.java:32)
at org.apmem.tools.layouts.FlowLayout.(FlowLayout.java:32)

    <org.apmem.tools.layouts.FlowLayout
                    android:id="@+id/container_tags"
                    xmlns:flow="http://schemas.android.com/apk/res-auto"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/container_download_option"
                    android:layout_marginTop="16dp"
                    android:gravity="center"
                    flow:weightDefault="1.0">
                </org.apmem.tools.layouts.FlowLayout>

**Comment by ApmeM** [comment]
Hi,

What version of this layout are you using?
This issue was some time before. Are you sure you are using the latest code?

**Comment by ravibhan90** [comment]
Hi , i am using version 1.9 .
compile 'org.apmem.tools:layouts:1.9@aar'
